// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          uuid.UUID   `json:"id"`
	PhoneNumber string      `json:"phone_number"`
	UserID      pgtype.UUID `json:"user_id"`
	NationalID  string      `json:"national_id"`
	KraPin      string      `json:"kra_pin"`
}

type Owner struct {
	ID          uuid.UUID   `json:"id"`
	PhoneNumber string      `json:"phone_number"`
	UserID      pgtype.UUID `json:"user_id"`
	NationalID  string      `json:"national_id"`
}

type Property struct {
	ID        uuid.UUID      `json:"id"`
	Type      string         `json:"type"`
	Price     pgtype.Numeric `json:"price"`
	Status    string         `json:"status"`
	Pictures  []byte         `json:"pictures"`
	Bedroom   int32          `json:"bedroom"`
	Bathroom  int32          `json:"bathroom"`
	Location  string         `json:"location"`
	Size      string         `json:"size"`
	Contact   string         `json:"contact"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	AgentID   uuid.UUID      `json:"agent_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type PropertyAgent struct {
	PropertyID uuid.UUID   `json:"property_id"`
	AgentID    pgtype.UUID `json:"agent_id"`
}

type PropertyOwner struct {
	PropertyID uuid.UUID   `json:"property_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
