// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Picture struct {
	ID          uuid.UUID `json:"id"`
	PropertyID  uuid.UUID `json:"property_id"`
	ImgUrl      string    `json:"img_url"`
	Description string    `json:"description"`
}

type Property struct {
	ID        uuid.UUID      `json:"id"`
	Type      string         `json:"type"`
	Price     pgtype.Numeric `json:"price"`
	Status    string         `json:"status"`
	Bedroom   int32          `json:"bedroom"`
	Bathroom  int32          `json:"bathroom"`
	Location  string         `json:"location"`
	Size      string         `json:"size"`
	Contact   string         `json:"contact"`
	CreatedAt time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	Role              string    `json:"role"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
