// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAgent(ctx context.Context, id uuid.UUID) error
	DeleteOwner(ctx context.Context, id uuid.UUID) error
	DeleteProperty(ctx context.Context, id uuid.UUID) error
	GetAgent(ctx context.Context, id uuid.UUID) (Agent, error)
	GetOwner(ctx context.Context, id uuid.UUID) (Owner, error)
	GetProperty(ctx context.Context, id uuid.UUID) (Property, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListOwners(ctx context.Context) ([]Owner, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) error
	UpdateOwner(ctx context.Context, arg UpdateOwnerParams) error
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
