name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:${{ env.POSTGRES_VERSION }}"
        env:
          POSTGRES_USER: ${{ env.USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
            - 5432:5432
        options:
          --health-cmd pg_isready -U ${{ env.USER }} -d ${{ env.DB_NAME }}
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install golang-migrate
        run: /
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test